project:
  type: website
  output-dir: docs

website:
  title: "pdnum-2023"
  navbar:
    left:
      - text: "sains-data"
        href: https://carlesoctav.github.io/sains-data-2023/


    right: 
      - icon: github
        href: https://github.com/carlesoctav/pdnum-2023

  sidebar:
    contents:
      - section: Module
        contents: module/*
      - section: Tugas
        contents: tugas-pd/*

  comments:
    giscus:
      repo: carlesoctav/pdnum-2023

format:
  html:
    theme: litera
    css: styles.css
    toc: true



