project:
  type: website
  output-dir: docs

website:
  title: "pdnum-2023"
  navbar:
    left:
      - text: "sains-data"
        href: https://carlesoctav.github.io/sains-data-2023/


    right: 
      - icon: github
        href: https://carlesoctav.github.io/pdnum-2023/

  sidebar:
    contents: module

format:
  html:
    theme: litera
    css: styles.css
    toc: true



